core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]


news/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('single/<str:news_slug>/', single_page, name='single'),
    path('category/<str:category_slug>/', category_page, name='category'),
]

news/models.py
from django.db import models


class Category(models.Model):
    slug = models.SlugField()
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='category_images/', blank=True, null=True)

    def __str__(self):
        return self.name


class News(models.Model):
    TAGS = (
        ('Yangi', 'Yangi'),
        ('Dolzarb', 'Dolzarb'),
        ('Qaynoq', 'Qaynoq'),
    )

    slug = models.SlugField()
    title = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)
    image = models.ImageField(upload_to='news_images/', blank=True, null=True)
    tags = models.CharField(max_length=150, choices=TAGS, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


news/views.py
from django.shortcuts import render
from .models import Category, News
import requests


def home_page(request):
    categories = Category.objects.all()
    news = News.objects.all().order_by('-created_at')
    context = {
        'categories': categories,
        'news': news,
    }
    return render(request, 'index.html', context=context)


def single_page(request, news_slug):
    news = News.objects.get(slug=news_slug)
    tranding_news = News.objects.all().order_by('-views')[:5]
    news.views += 1
    news.save()

    context = {
        'news': news,
        'tranding_news': tranding_news,
    }
    return render(request,'single.html', context=context)


def category_page(request, category_slug):
    categories = Category.objects.all()
    news = News.objects.filter(category__slug=category_slug)
    context = {
        "news": news,
        "categories": categories
    }
    return render(request,'category.html', context=context)


def contact_page(request):
    if request.method == 'POST':
        token = ''
        chat_id = -100
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        content = f"Ism: {name}\nE-Pochta: {email}\nMavzu: {subject}\n Xabar: {message}"

        url = f"https://api.telegram.org/bot{token}/sendMessage?chat_id={chat_id}&text={content}"
        requests.post(url)

    return render(request, 'contact.html')


templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    {% block title %}
    {% endblock %}
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">   

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>

    {% include 'includes/navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'includes/footer.html' %}


    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/category.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}


{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="container">
            <nav class="breadcrumb bg-transparent m-0 p-0">
                <a class="breadcrumb-item" href="#">Home</a>
                <a class="breadcrumb-item" href="#">Category</a>
                <span class="breadcrumb-item active">Technology</span>
            </nav>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- News With Sidebar Start -->
    <div class="container-fluid py-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row">
                        {% for new in news %}
                        <div class="col-lg-6">
                            <div class="position-relative mb-3">
                                <img class="img-fluid w-100" src="{{ new.image.url }}" style="object-fit: cover;">
                                <div class="overlay position-relative bg-light">
                                    <div class="mb-2" style="font-size: 14px;">
                                        <a href="">{{ new.category }}</a>
                                        <span class="px-1">/</span>
                                        <span>{{ new.created_at }}</span>
                                    </div>
                                    <a class="h4" href="">{{ new.title }}</a>
                                    <p class="m-0">{{ new.description }}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    
                    <div class="mb-3">
                        <a href=""><img class="img-fluid w-100" src="img/ads-700x70.jpg" alt=""></a>
                    </div>
                    
                    <div class="row">
                        {% for new in news %}
                        <div class="col-lg-6">
                            <div class="d-flex mb-3">
                                <img src="{{ new.image.url }}" style="width: 100px; height: 100px; object-fit: cover;">
                                <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                    <div class="mb-1" style="font-size: 13px;">
                                        <a href="">{{ new.category }}</a>
                                        <span class="px-1">/</span>
                                        <span>{{ new.created_at }}</span>
                                    </div>
                                    <a class="h6 m-0" href="{% url 'single' new.slug %}">{{ new.title }}</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <nav aria-label="Page navigation">
                              <ul class="pagination justify-content-center">
                                <li class="page-item disabled">
                                  <a class="page-link" href="#" aria-label="Previous">
                                    <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                  </a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                  <a class="page-link" href="#" aria-label="Next">
                                    <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                  </a>
                                </li>
                              </ul>
                            </nav>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 pt-3 pt-lg-0">
                    <!-- Social Follow Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Follow Us</h3>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #39569E;">
                                <small class="fab fa-facebook-f mr-2"></small><small>12,345 Fans</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #52AAF4;">
                                <small class="fab fa-twitter mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #0185AE;">
                                <small class="fab fa-linkedin-in mr-2"></small><small>12,345 Connects</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #C8359D;">
                                <small class="fab fa-instagram mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #DC472E;">
                                <small class="fab fa-youtube mr-2"></small><small>12,345 Subscribers</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #1AB7EA;">
                                <small class="fab fa-vimeo-v mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->

                    <!-- Popular News Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tranding</h3>
                        </div>
                        {% for new in news %}
                        <div class="d-flex mb-3">
                            <img src="{{ new.image.url }}" style="width: 100px; height: 100px; object-fit: cover;">
                            <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                <div class="mb-1" style="font-size: 13px;">
                                    <a href="">{{ new.category }}</a>
                                    <span class="px-1">/</span>
                                    <span>{{ new.created_at }}</span>
                                </div>
                                <a class="h6 m-0" href="">{{ new.title }}</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Popular News End -->

                    <!-- Tags Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tags</h3>
                        </div>
                        <div class="d-flex flex-wrap m-n1">
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Politics</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Business</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Corporate</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Sports</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Health</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Education</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Science</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Technology</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Foods</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Entertainment</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Travel</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Lifestyle</a>
                        </div>
                    </div>
                    <!-- Tags End -->
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- News With Sidebar End -->

{% endblock %}

templates/contact.html
{% extends 'base.html' %}


{% block title %}
{% endblock %}

{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="container">
            <nav class="breadcrumb bg-transparent m-0 p-0">
                <a class="breadcrumb-item" href="#">Home</a>
                <span class="breadcrumb-item active">Contact</span>
            </nav>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Contact Start -->
    <div class="container-fluid py-3">
        <div class="container">
            <div class="bg-light py-2 px-4 mb-3">
                <h3 class="m-0">Contact Us For Any Queries</h3>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="bg-light mb-3" style="padding: 30px;">
                        <h6 class="font-weight-bold">Get in touch</h6>
                        <p>Labore ipsum ipsum rebum erat amet nonumy, nonumy erat justo sit dolor ipsum sed, kasd lorem sit et duo dolore justo lorem stet labore, diam dolor et diam dolor eos magna, at vero lorem elitr</p>
                        <div class="d-flex align-items-center mb-3">
                            <i class="fa fa-2x fa-map-marker-alt text-primary mr-3"></i>
                            <div class="d-flex flex-column">
                                <h6 class="font-weight-bold">Our Office</h6>
                                <p class="m-0">123 Street, New York, USA</p>
                            </div>
                        </div>
                        <div class="d-flex align-items-center mb-3">
                            <i class="fa fa-2x fa-envelope-open text-primary mr-3"></i>
                            <div class="d-flex flex-column">
                                <h6 class="font-weight-bold">Email Us</h6>
                                <p class="m-0">info@example.com</p>
                            </div>
                        </div>
                        <div class="d-flex align-items-center">
                            <i class="fas fa-2x fa-phone-alt text-primary mr-3"></i>
                            <div class="d-flex flex-column">
                                <h6 class="font-weight-bold">Call Us</h6>
                                <p class="m-0">+012 345 6789</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="contact-form bg-light mb-3" style="padding: 30px;">
                        <div id="success"></div>
                        <form name="sentMessage" id="contactForm" novalidate="novalidate">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="control-group">
                                        <input type="text" class="form-control p-4" id="name" name="name" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name" />
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="control-group">
                                        <input type="email" class="form-control p-4" id="email" name="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email" />
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <input type="text" class="form-control p-4" id="subject" name="subject" placeholder="Subject" required="required" data-validation-required-message="Please enter a subject" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control" rows="4" id="message" name="message" placeholder="Message" required="required" data-validation-required-message="Please enter your message"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;" type="submit" id="sendMessageButton">Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
{% endblock %}

templates/includes/footer.html
<!-- Footer Start -->
<div class="container-fluid bg-light pt-5 px-sm-3 px-md-5">
  <div class="row">
    <div class="col-lg-3 col-md-6 mb-5">
      <a href="index.html" class="navbar-brand">
        <h1 class="mb-2 mt-n2 display-5 text-uppercase">
          <span class="text-primary">News</span>Room
        </h1>
      </a>
      <p>
        Volup amet magna clita tempor. Tempor sea eos vero ipsum. Lorem lorem
        sit sed elitr sed kasd et
      </p>
      <div class="d-flex justify-content-start mt-4">
        <a
          class="btn btn-outline-secondary text-center mr-2 px-0"
          style="width: 38px; height: 38px"
          href="#"
          ><i class="fab fa-twitter"></i
        ></a>
        <a
          class="btn btn-outline-secondary text-center mr-2 px-0"
          style="width: 38px; height: 38px"
          href="#"
          ><i class="fab fa-facebook-f"></i
        ></a>
        <a
          class="btn btn-outline-secondary text-center mr-2 px-0"
          style="width: 38px; height: 38px"
          href="#"
          ><i class="fab fa-linkedin-in"></i
        ></a>
        <a
          class="btn btn-outline-secondary text-center mr-2 px-0"
          style="width: 38px; height: 38px"
          href="#"
          ><i class="fab fa-instagram"></i
        ></a>
        <a
          class="btn btn-outline-secondary text-center mr-2 px-0"
          style="width: 38px; height: 38px"
          href="#"
          ><i class="fab fa-youtube"></i
        ></a>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 mb-5">
      <h4 class="font-weight-bold mb-4">Categories</h4>
      <div class="d-flex flex-wrap m-n1">
        {% for category in categories %}
        <a href="{% url 'category' category.slug %}" class="btn btn-sm btn-outline-secondary m-1">{{ category.name }}</a>
        {% endfor %}
      </div>
    </div>
    <div class="col-lg-3 col-md-6 mb-5">
      <h4 class="font-weight-bold mb-4">Tags</h4>
      <div class="d-flex flex-wrap m-n1">
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Politics</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Business</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Corporate</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Sports</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Health</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Education</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Science</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Technology</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Foods</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1"
          >Entertainment</a
        >
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Travel</a>
        <a href="" class="btn btn-sm btn-outline-secondary m-1">Lifestyle</a>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 mb-5">
      <h4 class="font-weight-bold mb-4">Quick Links</h4>
      <div class="d-flex flex-column justify-content-start">
        <a class="text-secondary mb-2" href="#"
          ><i class="fa fa-angle-right text-dark mr-2"></i>About</a
        >
        <a class="text-secondary mb-2" href="#"
          ><i class="fa fa-angle-right text-dark mr-2"></i>Advertise</a
        >
        <a class="text-secondary mb-2" href="#"
          ><i class="fa fa-angle-right text-dark mr-2"></i>Privacy & policy</a
        >
        <a class="text-secondary mb-2" href="#"
          ><i class="fa fa-angle-right text-dark mr-2"></i>Terms & conditions</a
        >
        <a class="text-secondary" href="#"
          ><i class="fa fa-angle-right text-dark mr-2"></i>Contact</a
        >
      </div>
    </div>
  </div>
</div>
<div class="container-fluid py-4 px-sm-3 px-md-5">
  <p class="m-0 text-center">
    &copy; <a class="font-weight-bold" href="#">Your Site Name</a>. All Rights
    Reserved.

    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
    Designed by
    <a class="font-weight-bold" href="https://htmlcodex.com">HTML Codex</a>
  </p>
</div>
<!-- Footer End -->

<!-- Back to Top -->
<a href="#" class="btn btn-dark back-to-top"><i class="fa fa-angle-up"></i></a>

templates/index.html
{% extends 'base.html' %}


{% block title %}
<title>Home page</title>
{% endblock %}


{% block content %}

    <!-- Main News Slider Start -->
    <div class="container-fluid py-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="owl-carousel owl-carousel-2 carousel-item-1 position-relative mb-3 mb-lg-0">
                        {% for n in news %}
                        <div class="position-relative overflow-hidden" style="height: 435px;">
                            <img class="img-fluid h-100" src="{{ n.image.url }}" style="object-fit: cover;">
                            <div class="overlay">
                                <div class="mb-1">
                                    <a class="text-white" href="">{{ n.category }}</a>
                                    <span class="px-2 text-white">/</span>
                                    <a class="text-white" href="">{{ n.created_at }}</a>
                                </div>
                                <a class="h2 m-0 text-white font-weight-bold" href="{% url 'single' n.slug %}">{{ n.title }}</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
                        <h3 class="m-0">Categories</h3>
                        <a class="text-secondary font-weight-medium text-decoration-none" href="">View All</a>
                    </div>
                    {% for category in categories %}
                    <div class="position-relative overflow-hidden" style="height: 80px;">
                        <img class="img-fluid w-100 h-100" src="{{ category.image.url }}" style="object-fit: cover;">
                        <a href="" class="overlay align-items-center justify-content-center h4 m-0 text-white text-decoration-none">
                            {{ category.name }}
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Main News Slider End -->


    <!-- Featured News Slider Start -->
    <div class="container-fluid py-3">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
                <h3 class="m-0">Featured</h3>
                <a class="text-secondary font-weight-medium text-decoration-none" href="">View All</a>
            </div>
            <div class="owl-carousel owl-carousel-2 carousel-item-4 position-relative">
                {% for new in news %}
                <div class="position-relative overflow-hidden" style="height: 300px;">
                    <img class="img-fluid w-100 h-100" src="{{ new.image.url }}" style="object-fit: cover;">
                    <div class="overlay">
                        <div class="mb-1" style="font-size: 13px;">
                            <a class="text-white" href="">{{ new.category }}</a>
                            <span class="px-1 text-white">/</span>
                            <a class="text-white" href="">{{ new.created_at }}</a>
                        </div>
                        <a class="h4 m-0 text-white" href="{% url 'single' new.slug %}">{{ new.title }}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    </div>
    <!-- Featured News Slider End -->


    <!-- Category News Slider Start -->
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                {% for category in categories %}
                {% if category.news_set.all %}
                <div class="col-lg-6 py-3">
                    <div class="bg-light py-2 px-4 mb-3">
                        <h3 class="m-0">{{ category.name }}</h3>
                    </div>
                    <div class="owl-carousel owl-carousel-3 carousel-item-2 position-relative">
                        {% for new in category.news_set.all %}
                        <div class="position-relative">
                            <img class="img-fluid w-100" src="{{ new.image.url }}" style="object-fit: cover;">
                            <div class="overlay position-relative bg-light">
                                <div class="mb-2" style="font-size: 13px;">
                                    <a href="">{{ new.category }}</a>
                                    <span class="px-1">/</span>
                                    <span>{{ new.created_at }}</span>
                                </div>
                                <a class="h4 m-0" href="{% url 'single' new.slug %}">{{ new.title }}</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    </div>
    <!-- Category News Slider End -->

    {% endblock %}